# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kris_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DryEraseMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=38)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrtuction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drymarker', to='kris_app.Instructor')),
            ],
        ),
    ]
